#include <stdio.h>
#include <string.h>
#include <inttypes.h>
#include <sys/mman.h>
#include <stdlib.h>
#include <math.h>
#include <unistd.h>
#include <signal.h>
#include <time.h>
#include <alchemy/task.h>
#include <alchemy/timer.h>
#include "ethercat.h"